name: example-1

services:
  database: # postgres
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: pass
    ports:
      - "5435:5432"

  web: # or frontend
    image: example-web # now it is the name of the image
    environment: # need it if postgres is named as database
      - SPRING_DATASOURCE_URL=jdbc:postgresql://database:5432/postgres
    build:
      context: . # current folder, or ./foo, /bar
      dockerfile: prod.Dockerfile
    ports:
      - "8083:8080"

